config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :properties do
    resources :bookings
  end
  resources :users do
    resources :bookings
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :user
    belongs_to :property

    validates :start_date, presence: true
    validates :number_of_guests, presence: true
    validates :number_of_guests, numericality: { only_integer: true }

    accepts_nested_attributes_for :property, reject_if: :all_blank

    # def property_attributes=(property_attributes)
    #     return if property_attributes.values.any? {|attribute| attribute == ""}
    #     property = Property.create(property_attributes)
    #     self.property = property
    #     self.save
    # end
end

app/models/property.rb
class Property < ApplicationRecord
    has_many :bookings
    has_many :users, through: :bookings
    validates :address, presence: true
    def full_address
        "#{self.address}, #{self.city}, #{self.state}" 
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :bookings
    has_many :properties, through: :bookings
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @user ||= User.first
    end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  def index
    if params[:property_id]
      @property = Property.find_by_id(params[:property_id])
      @bookings = @property.bookings
    else
      @bookings = Booking.all
    end
  end

  def new
    @property = Property.find_by_id(params[:property_id]) if params[:property_id]
    @booking = Booking.new
  end

  def create
    @booking = current_user.bookings.create(booking_params)
    redirect_to booking_path(@booking)
  end

  def show
    @booking = Booking.find_by_id(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :number_of_guests, :property_id, property_attributes: %i[address city state max_occupancy])
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

    def index
        @properties = Property.all
    end

    
    def show
        @property = Property.find_by_id(params[:id])
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>
<%=form_for @booking do |f|%>
  <%=f.label :start_date%>
  <%=f.date_field :start_date%>
  <%=f.label :number_of_guests%>
  <%=f.text_field :number_of_guests%>
  <%=f.label :property_id%>
  <%= f.collection_select :property_id, Property.all, :id, :full_address %>
  <%=f.submit%>
<%end%>

app/views/bookings/index.html.erb
<h1>All Bookings</h1>
<% @bookings.each do |booking| %>
  <p>A booking that starts on, <%=booking.start_date%></p>
<% end %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<%=form_for @booking do |f|%>
  <%if @property%>
    <h2>New Booking for <%=@property.full_address%></h2>
    <%=f.hidden_field :property_id, value:@property.id%>
  <%else%>
    <h3>Select a Property</h3>
    <%=f.label :property_id%>
    <%= f.collection_select :property_id, Property.all, :id, :full_address, include_blank: true %>
    <h3>Or Create a New Property</h3>
    <%= f.fields_for :property, Property.new do |property_field|%>
      <%= property_field.label :address%>
      <%= property_field.text_field :address%>
      <%= property_field.label :city%>
      <%= property_field.text_field :city%>
      <%= property_field.label :state%>
      <%= property_field.text_field :state%>
      <%= property_field.label :max_occupancy%>
      <%= property_field.number_field :max_occupancy%>
    <% end %>
  <%end%>
  <%=f.label :start_date%>
  <%=f.date_field :start_date%>
  <%=f.label :number_of_guests%>
  <%=f.text_field :number_of_guests%>
  <%=f.submit%>
<%end%>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>
<p>Check-in Date: <%=@booking.start_date%>
<p>Address: <%=@booking.property.address%></p>
<p>City: <%=@booking.property.city%></p>
<p>State: <%=@booking.property.state%></p>
<p>Number of Guests: <%=@booking.number_of_guests%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pod5Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/index.html.erb
<h1>All Properties</h1>
<% @properties.each do |property| %>
  <p>Address: <%=property.full_address%></p>
  <%=link_to "property details", property_path(property)%>
<% end %>

app/views/properties/show.html.erb
<h1>Property Details</h1>
<p>Location: <%=@property.full_address%></p>
<p>Max Occupancy: <%=@property.max_occupancy%></p>
<%=button_to "Book Property", new_property_booking_path(@property), :method => :get%>
<%=button_to "Booking History", property_bookings_path(@property), :method => :get%>
<%=button_to "Edit Property", edit_property_path(@property), :method => :get %>
<%=button_to "Delete Property", property_path(@property), :method => :delete %>